"""Added room configuration table

Revision ID: 1780ad3ce78d
Revises: 8e929aa6d627
Create Date: 2024-10-05 19:31:33.518446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780ad3ce78d'
down_revision: Union[str, None] = '8e929aa6d627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
