"""Added room configuration field

Revision ID: 620ce7c88821
Revises: 1780ad3ce78d
Create Date: 2024-10-12 12:15:02.727249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620ce7c88821'
down_revision: Union[str, None] = '1780ad3ce78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('configuration', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'configuration')
    # ### end Alembic commands ###
