"""Added bot configuration table

Revision ID: a1b2c3d4e5f6
Revises: 620ce7c88821
Create Date: 2025-11-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '620ce7c88821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configuration_config_name'), 'bot_configuration', ['config_name'], unique=False)
    op.create_index(op.f('ix_bot_configuration_key'), 'bot_configuration', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_configuration_key'), table_name='bot_configuration')
    op.drop_index(op.f('ix_bot_configuration_config_name'), table_name='bot_configuration')
    op.drop_table('bot_configuration')
    # ### end Alembic commands ###
