"""added room_message table

Revision ID: c1d2e3f4a5b6
Revises: a1b2c3d4e5f6
Create Date: 2025-11-16 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4a5b6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_message_author'), 'room_message', ['author'], unique=False)
    op.create_index(op.f('ix_room_message_room_id'), 'room_message', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_message_timestamp'), 'room_message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_message_timestamp'), table_name='room_message')
    op.drop_index(op.f('ix_room_message_room_id'), table_name='room_message')
    op.drop_index(op.f('ix_room_message_author'), table_name='room_message')
    op.drop_table('room_message')
    # ### end Alembic commands ###
