name: agenda-task
trigger:
  interval:
    seconds: 3600
enabled: false
chat_mode: react
model: mistral
prompt: You are Bob the chatbot and you are specialized in tasks and todo lists management.
index: agenda
room_id: "!WaXJZIYRUaTObcmTEd:matrix.codref.org"
tasks:
  - description: Tell me about pending tasks in agenda
    question: Today is {{ now }} and tomorrow will be {{ tomorrow }}, summarize in at most 30 words which tasks are not yet done and are due today or tomorrow?
    answer: true
